# Generated by Django 6.0.4 on 2026-04-28 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Response_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metadata", models.JSONField()),
            ],
            options={
                "verbose_name": "Response Table",
                "verbose_name_plural": "Response Tables",
                "db_table": "response_table",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Student_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Student_id", models.IntegerField(default=0, unique=True)),
                ("Name", models.CharField(max_length=200)),
                ("Contact", models.IntegerField()),
                ("Date_of_Birth", models.DateField()),
                ("Faculty", models.CharField(max_length=200)),
                ("Address", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Student Detail",
                "verbose_name_plural": "Student Details",
                "db_table": "student_details",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="User_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("family_no", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                ("contact_number", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=20)),
                ("age", models.IntegerField()),
            ],
            options={
                "verbose_name": "User Detail",
                "verbose_name_plural": "User Details",
                "db_table": "user_details",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Fee_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Semester", models.CharField(max_length=20)),
                ("Fee_amount", models.IntegerField()),
                ("Paid_amount", models.IntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_data.student_details",
                        to_field="Student_id",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Detail",
                "verbose_name_plural": "Fee Details",
                "db_table": "fee_details",
                "ordering": ["-id"],
            },
        ),
    ]
